kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../default
  - oauth_route.yaml
  - scm_route.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/default?ref=dbbad2bacb3a2fc619647c6a0514dc9aa88f5c37


images:
  - name: quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: 0.4.6
  - name:  quay.io/redhat-appstudio/service-provider-integration-oauth
    newName:  quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: 0.4.6
  - name: quay.io/redhat-appstudio/service-provider-integration-scm-file-retriever-server
    newName:  quay.io/redhat-appstudio/service-provider-integration-scm-file-retriever-server
    newTag: next