apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-file-retriever-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: service-provider-scm-file-retriever-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-provider-scm-file-retriever-server
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
          - /spi-file
          image: quay.io/redhat-appstudio/service-provider-integration-scm-file-retriever-server
          name: server
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: file-retriever-server-sa
      terminationGracePeriodSeconds: 10
