kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: service-provider-integration-scm

resources:
- deployment.yaml
- service-account.yaml
- service.yaml
