kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../default
  - ../namespace
  - ingress.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/k8s?ref=c36682a4fd7dbac2e7303637e0cc4c5ff958cfd4


patches:
  - target:
      kind: Ingress
      name: spi-oauth-ingress
    path: ingress-patch.json